server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /patient-service
spring:
  application:
    name: patient-service
  data:
    mongodb:
      uri: mongodb+srv://patient-service:pVRZ6QrLH31hcEgW@cluster0.vacjkqi.mongodb.net/patientService
      database: patientService
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer