server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /patient-service
spring:
  application:
    name: patient-service
  data:
    mongodb:
      uri: mongodb+srv://patient-service:pVRZ6QrLH31hcEgW@cluster0.vacjkqi.mongodb.net/patientService
      database: patientService
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect